# Generated by Django 5.2.4 on 2025-08-07 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_picture', models.ImageField(blank=True, null=True, upload_to='room_pictures/')),
                ('related_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Booking.room')),
            ],
        ),
    ]
