# Generated by Django 5.2.4 on 2025-08-11 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0003_amenity'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='amenities',
            field=models.ManyToManyField(blank=True, to='Booking.amenity'),
        ),
    ]
