# Generated by Django 5.2.4 on 2025-08-11 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0004_bookings_amenities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='amenities',
        ),
        migrations.AddField(
            model_name='room',
            name='amenities',
            field=models.ManyToManyField(blank=True, to='Booking.amenity'),
        ),
    ]
