# Generated by Django 5.2.4 on 2025-08-11 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0005_remove_bookings_amenities_room_amenities'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='min_guests',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='room',
            name='max_guests',
            field=models.IntegerField(default=2),
        ),
    ]
