# Generated by Django 5.2.4 on 2025-08-13 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0006_room_min_guests_alter_room_max_guests'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='area',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=10),
        ),
    ]
