# Generated by Django 5.2.4 on 2025-08-25 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0007_room_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='guests',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
